name: Check syntax

on:
  push:

jobs:
  build:
    name: Format content with Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: latest

      - name: Prettify code
        uses: creyD/prettier_action@31355f8eef017f8aeba2e0bc09d8502b13dbbad1 # v4.3
        with:
          prettier_options: --write **/*.{ts,js,md}
          github_token: ${{ github.token }}
